from typing import List, Optional
from uuid import UUID
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from fastapi import HTTPException

from app.models.board import Board
from app.models.column import Column
from app.models.task import Task
from app.models.subtask import Subtask as SubtaskModel
from app.schemas.board import BoardCreate, BoardUpdate
from app.schemas.column import ColumnCreate, ColumnUpdate
from app.schemas.task import TaskCreate, TaskUpdate
from app.schemas.subtask import SubtaskCreate, SubtaskUpdate
from app.services.security_manager import get_security_manager
from app.domain.enums import EncryptionStatus
from app.models.board_template import BoardTemplate

security_manager = get_security_manager()

class BoardOps:
    @staticmethod
    async def get_boards(db: AsyncSession, user_id: Optional[UUID] = None) -> List[Board]:
        from app.models.board_member import BoardMember
        query = select(Board)
        if user_id:
            query = query.join(BoardMember).where(BoardMember.user_id == user_id)
        
        result = await db.execute(query)
        boards = result.scalars().all()
        for board in boards:
            security_manager.process_board_after_load(board)
        return boards
    
    @staticmethod
    async def get_board(db: AsyncSession, board_id: UUID) -> Optional[Board]:
        result = await db.execute(
            select(Board)
            .where(Board.id == board_id)
            .options(selectinload(Board.columns).selectinload(Column.tasks).selectinload(Task.subtasks))
        )
        board = result.scalar_one_or_none()
        if board:
            security_manager.process_board_after_load(board)
            for col in board.columns:
                for task in col.tasks:
                    security_manager.process_task_after_load(task, board.encryption_status)
        return board
    
    @staticmethod
    async def create_board(db: AsyncSession, board_in: BoardCreate, owner_id: UUID) -> Board:
        #It converts the Pydantic input (board_in) into a dictionary and uses it to create a new Board object by unpacking the fields as arguments.
        board = Board(**board_in.model_dump())
        security_manager.process_board_for_storage(board)
        db.add(board)
        """await db.flush() sends all pending changes (like inserts/updates) to the database without committing the transaction, so things like 
        autogenerated IDs become available but can still be rolled back."""
        await db.flush()

        #Create OWNER member
        from app.models.board_member import BoardMember
        from app.domain.enums import BoardRole
        member = BoardMember(board_id=board.id, user_id=owner_id, role=BoardRole.OWNER)
        db.add(member)
        await db.flush()
        
        security_manager.process_board_after_load(board)
        return board
    
    @staticmethod
    async def update_board(db: AsyncSession, board_id: UUID, board_in: BoardUpdate) -> Optional[Board]:
        board = await db.get(Board, board_id)
        if not board:
            return None
        
        update_data = board_in.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(board, key, value)

        security_manager.process_board_for_storage(board)
        await db.flush()
        security_manager.process_board_after_load(board)
        return board
    
    @staticmethod
    async def delete_board(db: AsyncSession, board_id: UUID) -> bool:
        board = await db.get(Board, board_id)
        if not board:
            return False
        await db.delete(board)
        return True
    
    #Column Ops
    @staticmethod
    async def create_column(db: AsyncSession, column_in: ColumnCreate) -> Column:
        column = Column(**column_in.model_dump())
        db.add(column)
        await db.flush()
        return column

    @staticmethod
    async def update_column(db: AsyncSession, column_id: UUID, column_in: ColumnUpdate) -> Optional[Column]:
        column = await db.get(Column, column_id)
        if not column:
            return None
        
        update_data = column_in.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(column, key, value)

        await db.flush()
        return column
    
    @staticmethod
    async def delete_column(db: AsyncSession, column_id: UUID) -> bool:
        column = await db.get(Column, column_id)
        if not column:
            return False
        await db.delete(column)
        return True
    
    #Task Ops
    @staticmethod
    async def create_task(db: AsyncSession, task_in: TaskCreate) -> Task:
        #WIP - Work in progress  Limit Check 
        col = await db.get(Column, task_in.column_id)
        if col and col.wip_limit :
            from sqlalchemy import func
            count_result = await db.execute(
                select(func.count(Task.id)).where(Task.column_id == col.id)
            )
            current_count = count_result.scalar()
            if current_count >= col.wip_limit:
                raise HTTPException(
                    status_code=400, #Means Bad Request 
                    detail=f"Column '{col.name}' has reached its WIP limit of {col.wip_limit}."
                )
            '''It converts the Pydantic input (task_in) into a dictionary and uses it to create a 
            new Task object by unpacking its fields as arguments.
            model_dump() converts a Pydantic model instance into a Python dictionary of its data.'''
            task = Task(**task_in.model_dump())

            #Fetch Board for encryption and custom fields schema 
            result = await db.execute(
                select(Board)
                .join(Column)
                .where(Column.id == task_in.column_id)
            )
            '''scalar()- Returns the first column of the first row, or None if no result.
            scalar_one_or_none() - Returns one scalar value or None
            scalar_one() - Returns exactly one scalar value
            scalars() - Returns all scalar values as an iterable
            _source_supports_scalars - Internal flag (not for direct use) . Indicates whether the result supports scalar extraction'''
            board = result.scalar()
            board_enc = board.encryption_status if board else EncryptionStatus.DISABLED

            #Custom Fields Validation
            if board and "custom_fields_schema" in board.settings:
                from app.services.custom_fields_service import CustomFieldsService
                errors = CustomFieldsService.validate_custom_fields(
                    task.custom_fields,
                    board.settings["custom_fields_schema"]
                )
                if errors:
                    from fastapi import HTTPException
                    raise HTTPException(
                        status_code=400,
                        detail={"errors": errors}
                    )
                
            security_manager.process_task_for_storage(task, board_enc)
            db.add(task)
            await db.flush()
            security_manager.process_task_after_load(task, board_enc)
            return task
        
    @staticmethod
    async def update_task(db: AsyncSession, task_id: UUID, task_in: TaskUpdate) -> Optional[Task]:
        task = await db.get(Task, task_id)
        if not task:
            return None
        
        update_data = task_in.model_dump(exclude_unset=True)

        # Fetch Board for encryption and custom fields schema (always needed)
        result = await db.execute(
            select(Board)
            .join(Column)
            .where(Column.id == task.column_id)
        )
        board = result.scalar()
        board_enc = board.encryption_status if board else EncryptionStatus.DISABLED

        #WIP Limit Check
        old_col_id = task.column_id
        if "column_id" in update_data and update_data["column_id"] != old_col_id:
            new_col_id = update_data["column_id"]
            new_col = await db.get(Column, new_col_id)
            if new_col and new_col.wip_limit:
                from sqlalchemy import func
                count_result = await db.execute(
                    select(func.count(Task.id)).where(Task.column_id == new_col_id)
                )
                current_count = count_result.scalar()
                if current_count >= new_col.wip_limit:
                    raise HTTPException(
                        status_code=400,
                        detail=f"Column '{new_col.name}' has reached its WIP limit of {new_col.wip_limit}."
                    )
                
                #Trigger Automations
                from app.services.automation_service import AutomationService
                await AutomationService.process_task_move(db, task, old_col_id, new_col_id)

        #Custom Fields Validation
        if board and "custom_fields_schema" in board.settings:
            from app.services.custom_fields_service import CustomFieldsService
            current_fields = task.custom_fields.copy() if task.custom_fields else {}
            if "custom_fields" in update_data:
                current_fields.update(update_data["custom_fields"])

            errors = CustomFieldsService.validate_custom_fields(
                current_fields,
                board.settings["custom_fields_schema"]
            )

            if errors:
                raise HTTPException(
                    status_code=400,
                    detail={"errors": errors}
                )
            
        for key,value in update_data.items():
            setattr(task, key, value)

        security_manager.process_task_for_storage(task, board_enc)
        await db.flush()
        security_manager.process_task_after_load(task, board_enc)
        return task
    
    @staticmethod
    async def delete_task(db: AsyncSession, task_id: UUID) -> bool:
        task = await db.get(Task, task_id)
        if not task:
            return False
        await db.delete(task)
        return True
    
    @staticmethod
    async def get_task(db: AsyncSession, task_id: UUID, include_linked_tasks: bool = False) -> Optional[Task]:
        from sqlalchemy.orm import selectinload
        from app.models.task_link import TaskLink
        
        options = [selectinload(Task.subtasks)]
        if include_linked_tasks:
            options.extend([
                selectinload(Task.source_links).selectinload(TaskLink.target_task),
                selectinload(Task.target_links).selectinload(TaskLink.source_task)
            ])
        else:
            options.extend([
                selectinload(Task.source_links),
                selectinload(Task.target_links)
            ])

        result = await db.execute(
            select(Task)
            .where(Task.id == task_id)
            .options(*options)
        )
        task = result.scalar_one_or_none()
        if task:
            # Fetch Board for encryption
            board_result = await db.execute(
                select(Board)
                .join(Column)
                .where(Column.id == task.column_id)
            )
            board = board_result.scalar()
            board_enc = board.encryption_status if board else EncryptionStatus.DISABLED
            security_manager.process_task_after_load(task, board_enc)
            
            # Combine links for the schema
            task.links = task.source_links + task.target_links
            
        return task
    
    #Subtask Ops
    @staticmethod
    async def create_subtask(db: AsyncSession, subtask_in: SubtaskCreate) -> SubtaskModel:
        subtask = SubtaskModel(**subtask_in.model_dump())
        db.add(subtask)
        await db.flush()
        return subtask
    
    @staticmethod
    async def update_subtask(db: AsyncSession, subtask_id: UUID, subtask_in: SubtaskUpdate) -> Optional[SubtaskModel]:
        subtask = await db.get(SubtaskModel, subtask_id)
        if not subtask:
            return None
        
        update_data = subtask_in.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(subtask, key, value)

        await db.flush()
        return subtask
    
    @staticmethod
    async def delete_subtask(db: AsyncSession, subtask_id: UUID) -> bool:
        subtask = await db.get(SubtaskModel, subtask_id)
        if not subtask:
            return False
        await db.delete(subtask)
        return True

    # Task Link Ops
    @staticmethod
    async def create_task_link(db: AsyncSession, source_task_id: UUID, link_in: 'TaskLinkCreate') -> 'TaskLinkModel':
        from app.models.task_link import TaskLink as TaskLinkModel
        # Check if link already exists
        result = await db.execute(
            select(TaskLinkModel).where(
                TaskLinkModel.source_task_id == source_task_id,
                TaskLinkModel.target_task_id == link_in.target_task_id,
                TaskLinkModel.link_type == link_in.link_type
            )
        )
        if result.scalar_one_or_none():
             from fastapi import HTTPException
             raise HTTPException(status_code=400, detail="Link already exists")
        
        link = TaskLinkModel(
            source_task_id=source_task_id,
            target_task_id=link_in.target_task_id,
            link_type=link_in.link_type
        )
        db.add(link)
        await db.flush()
        return link

    @staticmethod
    async def delete_task_link(db: AsyncSession, link_id: UUID) -> bool:
        from app.models.task_link import TaskLink as TaskLinkModel
        link = await db.get(TaskLinkModel, link_id)
        if not link:
            return False
        await db.delete(link)
        return True
    
    @staticmethod
    async def get_task_links(db: AsyncSession, task_id: UUID):
        from app.models.task_link import TaskLink as TaskLinkModel
        from sqlalchemy import or_
        result = await db.execute(
            select(TaskLinkModel).where(
                or_(
                    TaskLinkModel.source_task_id == task_id,
                    TaskLinkModel.target_task_id == task_id
                )
            )
        )
        return result.scalars().all()

    # Member Ops
    @staticmethod
    async def get_board_members(db: AsyncSession, board_id: UUID):
        from app.models.board_member import BoardMember
        result = await db.execute(
            select(BoardMember).where(BoardMember.board_id == board_id)
        )
        return result.scalars().all()

    @staticmethod
    async def add_board_member(db: AsyncSession, board_id: UUID, user_id: UUID, role: str):
        from app.models.board_member import BoardMember
        from app.domain.enums import BoardRole
        
        # Check if already a member
        result = await db.execute(
            select(BoardMember).where(BoardMember.board_id == board_id, BoardMember.user_id == user_id)
        )
        if result.scalar_one_or_none():
            from fastapi import HTTPException
            raise HTTPException(status_code=400, detail="User is already a member of this board")
            
        member = BoardMember(board_id=board_id, user_id=user_id, role=role)
        db.add(member)
        await db.flush()
        return member

    @staticmethod
    async def update_board_member(db: AsyncSession, board_id: UUID, user_id: UUID, role: str):
        from app.models.board_member import BoardMember
        result = await db.execute(
            select(BoardMember).where(BoardMember.board_id == board_id, BoardMember.user_id == user_id)
        )
        member = result.scalar_one_or_none()
        if not member:
            return None
            
        member.role = role
        await db.flush()
        return member

    @staticmethod
    async def remove_board_member(db: AsyncSession, board_id: UUID, user_id: UUID):
        from app.models.board_member import BoardMember
        from app.domain.enums import BoardRole
        result = await db.execute(
            select(BoardMember).where(BoardMember.board_id == board_id, BoardMember.user_id == user_id)
        )
        member = result.scalar_one_or_none()
        if not member:
            return False

        # Prevent removing the last owner
        if member.role == BoardRole.OWNER:
            owner_count_result = await db.execute(
                select(func.count(BoardMember.id)).where(
                    BoardMember.board_id == board_id,
                    BoardMember.role == BoardRole.OWNER
                )
            )
            owner_count = owner_count_result.scalar()
            if owner_count <= 1:
                raise HTTPException(
                    status_code=400,
                    detail="Cannot remove the last owner of a board."
                )

        await db.delete(member)
        return True

    # Template Ops
    @staticmethod
    async def get_templates(db: AsyncSession, user_id: Optional[UUID] = None) -> List[BoardTemplate]:
        """Get templates visible to the user (own + public)."""
        from sqlalchemy import or_
        query = select(BoardTemplate)
        if user_id:
            query = query.where(
                or_(
                    BoardTemplate.owner_user_id == user_id,
                    BoardTemplate.is_public == True
                )
            )
        else:
            query = query.where(BoardTemplate.is_public == True)
        result = await db.execute(query)
        return result.scalars().all()

    @staticmethod
    async def get_template(db: AsyncSession, template_id: UUID) -> Optional[BoardTemplate]:
        """Get a single template by ID."""
        return await db.get(BoardTemplate, template_id)

    @staticmethod
    async def create_template(db: AsyncSession, template_in, owner_id: UUID) -> BoardTemplate:
        """Create a new board template."""
        template_data = template_in.model_dump()
        template = BoardTemplate(**template_data, owner_user_id=owner_id)
        db.add(template)
        await db.flush()
        return template

    @staticmethod
    async def update_template(db: AsyncSession, template_id: UUID, template_in) -> Optional[BoardTemplate]:
        """Update an existing template."""
        template = await db.get(BoardTemplate, template_id)
        if not template:
            return None
        update_data = template_in.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(template, key, value)
        await db.flush()
        return template

    @staticmethod
    async def delete_template(db: AsyncSession, template_id: UUID) -> bool:
        """Delete a template."""
        template = await db.get(BoardTemplate, template_id)
        if not template:
            return False
        await db.delete(template)
        return True

    @staticmethod
    async def create_board_from_template(
        db: AsyncSession, template_id: UUID, board_name: str,
        owner_id: UUID, description: Optional[str] = None
    ) -> Board:
        """Create a new board from a template, including its columns and settings."""
        from fastapi import HTTPException

        template = await db.get(BoardTemplate, template_id)
        if not template:
            raise HTTPException(status_code=404, detail="Template not found")

        # Extract payload
        payload = template.payload or {}
        board_settings = payload.get("settings", {})
        custom_fields_schema = payload.get("custom_fields_schema", [])
        if custom_fields_schema:
            board_settings["custom_fields_schema"] = custom_fields_schema

        # Create board
        board = Board(
            name=board_name,
            description=description or template.description,
            settings=board_settings,
        )
        security_manager.process_board_for_storage(board)
        db.add(board)
        await db.flush()

        # Create OWNER member
        from app.models.board_member import BoardMember
        from app.domain.enums import BoardRole
        member = BoardMember(board_id=board.id, user_id=owner_id, role=BoardRole.OWNER)
        db.add(member)

        # Create columns from template
        columns_payload = payload.get("columns", [])
        for col_data in columns_payload:
            col = Column(
                board_id=board.id,
                name=col_data.get("name", "Untitled"),
                position=col_data.get("position", 0),
                wip_limit=col_data.get("wip_limit"),
                settings=col_data.get("settings", {}),
            )
            db.add(col)

        await db.flush()
        security_manager.process_board_after_load(board)
        return board
