#!/bin/bash
set -e

BOARD_DATABASE_NAME=${BOARD_DATABASE_NAME:-board_db}

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  SELECT 'CREATE DATABASE "${BOARD_DATABASE_NAME}"'
  WHERE NOT EXISTS (
    SELECT FROM pg_database WHERE datname = '${BOARD_DATABASE_NAME}'
  )\gexec
EOSQL
