services:
  auth_api:
    build: .
    container_name: auth_api
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - default
      - snaprise_shared

networks:
  default:
    name: auth_service_default
  snaprise_shared:
    external: true
    name: snaprise_shared
