"""Phase2.1

Revision ID: 74d891779aa7
Revises: 887766554433
Create Date: 2026-05-15 23:56:01.905752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d891779aa7'
down_revision: Union[str, None] = '887766554433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='boardrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    op.create_index(op.f('ix_board_members_user_id'), 'board_members', ['user_id'], unique=False)
    op.create_table('column_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_restriction', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='boardrole'), nullable=True),
    sa.Column('access_type', sa.Enum('READ', 'WRITE', name='accesstype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_access_column_id'), 'column_access', ['column_id'], unique=False)
    op.create_index(op.f('ix_column_access_user_id'), 'column_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_access_user_id'), table_name='column_access')
    op.drop_index(op.f('ix_column_access_column_id'), table_name='column_access')
    op.drop_table('column_access')
    op.drop_index(op.f('ix_board_members_user_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_table('board_members')
    # ### end Alembic commands ###
